.PHONY: clean All

All:
	@echo "----------Building project:[ Kaleidoscope - Debug ]----------"
	@cd "Kaleidoscope" && $(MAKE) -f  "Kaleidoscope.mk"
clean:
	@echo "----------Cleaning project:[ Kaleidoscope - Debug ]----------"
	@cd "Kaleidoscope" && $(MAKE) -f  "Kaleidoscope.mk" clean
